name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build_whl:
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.10', '3.13']
    if: github.actor != 'mfd-intel-bot'
    uses: ./.github/workflows/build_upload_whl.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      REPOSITORY_NAME: ${{ github.repository }}
      BRANCH_NAME: ${{ github.ref_name }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      RELEASE_BUILD: true
      PROJECT_NAME: 'mfd-code-quality'
