name: CI Build - Release Mode

on:
  workflow_dispatch:

jobs:
  publish_pypi:
    strategy:
      fail-fast: false
      matrix:
        include:
        - python_version: '3.10'
          release_steps: true
        - python_version: '3.13'
          release_steps: false
    uses: ./.github/workflows/build_upload_whl.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      REPOSITORY_NAME: ${{ github.repository }}
      BRANCH_NAME: ${{ github.ref_name }}
      PYTHON_VERSION: ${{ matrix.python_version }}
      PROJECT_NAME: 'mfd-code-quality'
      RELEASE_STEPS: ${{ matrix.release_steps }}
      RELEASE_BUILD: true
      JOB_NAME: 'publish_pypi'
  publish_release:
    needs: publish_pypi
    if: ${{ always() }}
    uses: ./.github/workflows/publish_release.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      REPOSITORY_NAME: ${{ github.repository }}
      BRANCH_NAME: ${{ github.ref_name }}
